apiVersion: v1
kind: Service
metadata:
  name: alert-api
  namespace: alert-ai
spec:
  ports:
  - name: 8000-tcp
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
  selector:
    app: alert-api
