global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          project: "ai"
          app: "mysql"
          ip: "192.168.100.101"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules"
